spring.application.name=trainer-service

#postgres
spring.datasource.url=jdbc:postgresql://gym-main-db.ccf002y008za.us-east-1.rds.amazonaws.com:5432/trainer
spring.datasource.username=postgres
spring.datasource.password=sql99999
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#actuator health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

#eureka client config
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true