version: "3.8"

services:
  trainee-service:
    build:
      context: ./trainee-service
    ports:
      - 8081:8080
    networks:
      - app-network
    depends_on:
      - postgres
      - service-registry
    container_name: trainee-service

  trainer-service:
    build:
      context: ./trainer-service
    ports:
      - 8082:8080
    networks:
      - app-network
    depends_on:
      - postgres
      - service-registry
    container_name: trainer-service

  trainee-trainer-relationship-service:
    build:
      context: ./trainee-trainer-relationship-service
    ports:
      - 8083:8080
    networks:
      - app-network
    depends_on:
      - postgres
      - service-registry
    container_name: trainee-trainer-relationship-service

  training-type-service:
    build:
      context: ./training-type-service
    ports:
      - 8084:8080
    networks:
      - app-network
    depends_on:
      - postgres
      - service-registry
    container_name: training-type-service

  user-service:
    build:
      context: ./user-service
    ports:
      - 8085:8080
    networks:
      - app-network
    depends_on:
      - postgres
      - service-registry
    container_name: user-service

  training-service:
    build:
      context: ./training-service
    ports:
      - 8086:8080
    networks:
      - app-network
    depends_on:
      - postgres
      - service-registry
    container_name: training-service

  user-orchestration-service:
    build:
      context: ./user-orchestration-service
    ports:
      - 8087:8080
    networks:
      - app-network
    depends_on:
      - service-registry
      - user-service
      - trainee-service
      - trainer-service
      - trainee-trainer-relationship-service
    container_name: user-orchestration-service

  service-registry:
    build:
      context: ./service-registry
    ports:
      - 8761:8761
    networks:
      - app-network
    container_name: service-registry

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql001
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    container_name: postgres

networks:
  app-network:

volumes:
  postgres-data:
