spring.application.name=gateway
server.port=9999

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=authentication-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://authentication-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/authentication/**

spring.cloud.gateway.server.webflux.routes[1].id=user-orchestration-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-orchestration-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/trainer/**
spring.cloud.gateway.server.webflux.routes[1].predicates[1]=Path=/trainee/**
spring.cloud.gateway.server.webflux.routes[1].predicates[2]=Path=/trainee-trainer-relationship/**

spring.cloud.gateway.server.webflux.routes[2].id=training-orchestration-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://training-orchestration-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/training/**

#eureka
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#authentication service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://authentication-service:9000/.well-known/jwks.json

#actuator health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always