spring.application.name=trainer-workload-service

#eureka client config
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#actuator health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

#aws sqs
spring.cloud.aws.sqs.enabled=true
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.sqs.endpoint=https://sqs.us-east-1.amazonaws.com/281328144926/Gym-Queue